version: '3.7'


services:
  grafana:
    image: grafana/grafana:latest 
    ports:
      - target: 3000
        published: 3000
        mode: host
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
