version: '3.7'

networks:
  traefik-net:
    external: true

services:
  grafana:
    build:
      context: ./grafana
      dockerfile: Dockerfile 
    image:  grafana/grafana:latest 
    ports:
      - target: 3000
        published: 3000
        mode: host
    networks:
      - traefik-net
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.labels.fe.grafana == true
